package ca.adera1220.mhwbgcharactertracker

import com.google.firebase.database.Exclude


data class CharSheet(
    val id: String = "",
    val playerName: String = "",
    val characterName: String = "",
    val campaignName: String = "",
    val palicoName: String = "",
    val weaponType: String = "",
    val potionCount: String = "0",
    val dayCount: String = "0",
    val weaponList: Map<String, Boolean> = mapOf<String, Boolean>(
        "1Hunter\\'s Bow" to false,
        "2Hunter\\'s Stoutbow" to false,
        "2Steel Bow" to false,
        "3Alloy Bow" to false,
        "3Blazing Bow" to false,
        "3Blooming Arch" to false,
        "3Diablos Bow" to false,
        "3Hunter\\'s Proudbow" to false,
        "3Kulu Arrow" to false,
        "3Pulsar Bow" to false,
        "4Anja Arch" to false,
        "4Archer\\'s Dance" to false,
        "4Datura String" to false,
        "4Diablos Coilbender" to false,
        "4Flying Kadachi Strike" to false,
        "4Icesteel Bow" to false,
        "4Nergal Whisper" to false,
        "5Daora\\'s Sagittarii" to false,
        "5Doom\\'s Shaft" to false,
        "1Bone Strongarm" to false,
        "2Hard Bone Strongarm" to false,
        "2Elite Commission Axe" to false,
        "3Chrome Guardian" to false,
        "3Diablos Wall" to false,
        "3Jagras Strongarm" to false,
        "3Mighty Strongarm" to false,
        "3Mudslide Blade" to false,
        "3Pulsar Strongarm" to false,
        "4Daora\\'s Casca" to false,
        "4Diablos Tyrannis" to false,
        "4Jagras Escudo" to false,
        "4Jyura Depth" to false,
        "4Kadachi Kaina" to false,
        "4Nergal Lacerator" to false,
        "5Daora\\'s Thwartoise" to false,
        "5Devistation\\'s Thorns" to false,
        "1Bone Hatchets" to false,
        "2Dual Slicers" to false,
        "2Wild Hatchets" to false,
        "3Blazing Hatchets" to false,
        "3Chrome Slicers" to false,
        "3Diablos Hatchets" to false,
        "3Madness Pangas" to false,
        "3Pulsar Hatchets" to false,
        "3Rending Beaks" to false,
        "3Strong Hatchets" to false,
        "4Anja Cyclone" to false,
        "4Arcanaria" to false,
        "4Diablos Clubs" to false,
        "4Jyura Hatchets" to false,
        "4Kadachi Claws" to false,
        "4Nergal Gouge" to false,
        "4Twin Nails" to false,
        "5Decimation Claws" to false,
        "5Fire and Ice" to false,
        "1Bone Blade" to false,
        "2Bone Slasher" to false,
        "2Buster Blade" to false,
        "3Blooming Blade" to false,
        "3Carapace Buster" to false,
        "3Chrome Razor" to false,
        "3Flame Blade" to false,
        "3Giant Jawblade" to false,
        "3Jagras Blade" to false,
        "4Barroth Shredder" to false,
        "4Datura Blaze" to false,
        "4Icesteel Edge" to false,
        "4Jagras Hacker" to false,
        "4Nergal Judicator" to false,
        "4Red Wing" to false,
        "5Daora\\'s Decimator" to false,
        "5Pergation\\'s Atrocity" to false,
        "1Bone Gunlance" to false,
        "2Bone Cannon" to false,
        "2Steel Gunlance" to false,
        "3Carapace Cannon" to false,
        "3Chrome Gunlance" to false,
        "3Great Bone Gunlance" to false,
        "3Jagras Gunlance" to false,
        "3Madness Gunlance" to false,
        "3Rath Gunlance" to false,
        "3Barroth Blaster" to false,
        "4Glutton Gunlance" to false,
        "4Icesteel Gunlance" to false,
        "4Jyura Buster" to false,
        "4Nergal Ram" to false,
        "4Red Rook" to false,
        "5Daora\\'s Brigia" to false,
        "5Eradication Flame" to false,
        "1Bone Bludgeon" to false,
        "2Fossil Bludgeon" to false,
        "2Iron Demon" to false,
        "3Blazing Hammer" to false,
        "3Blooming Hammer" to false,
        "3Carapace Sledge" to false,
        "3Diablos Sledge" to false,
        "3Grand Rock" to false,
        "3Iron Arch Demon" to false,
        "3Kulu Beak" to false,
        "4Anja Striker" to false,
        "4Barroth Breaker" to false,
        "4Buon Fiore" to false,
        "4Crushing Beak" to false,
        "4Diablos Shatterer" to false,
        "4Icesteel Hammer" to false,
        "4Nergal Crusher" to false,
        "5Daora\\'s Colossus" to false,
        "5Obliteration\\'s Footfall" to false,
        "1Bone Shooter" to false,
        "2Heavy Shooter" to false,
        "2Steel Assault" to false,
        "3Blooming Shooter" to false,
        "3Chrome Assault" to false,
        "3Diablos Shooter" to false,
        "3Jagras Assault" to false,
        "3Power Shooter" to false,
        "3Pulsar Shooter" to false,
        "4Datura Blaster" to false,
        "4Dual Threat" to false,
        "4Jagras Cannon" to false,
        "4Kadachi Lion" to false,
        "4Nergal Roar" to false,
        "4Teostra\\'s Artillery" to false,
        "5Destruction\\'s Fusillade" to false,
        "5Teostra\\'s Flames" to false,
        "1Bone Horn" to false,
        "2Great Bagpipe" to false,
        "2Hard Bone Horn" to false,
        "3Aqua Bagpipe" to false,
        "3Blazing Horn" to false,
        "3Blooming Horn" to false,
        "3Fortissimo" to false,
        "3Heavy Bone Horn" to false,
        "3Thunder Gaida" to false,
        "4Anja Barone" to false,
        "4Datura Horn" to false,
        "4Lightning Drum" to false,
        "4Water Tamtam" to false,
        "4Nergal Groove" to false,
        "4Teostra\\'s Tiple" to false,
        "5Desolation\\'s Overture" to false,
        "5Teostra\\'s Orphee" to false,
        "1Bone Rod" to false,
        "2Hard Bone Rod" to false,
        "2Steel Blade" to false,
        "3Aerial Magus" to false,
        "3Blooming Glaive" to false,
        "3Chrome Blade" to false,
        "3Diablos Rod" to false,
        "3Flame Glaive" to false,
        "3Flammenkafer" to false,
        "3Kulu Blade" to false,
        "4Daora\\'s Entom" to false,
        "4Datura Blade" to false,
        "4Gnashing Flamm." to false,
        "4Nergal Reaper" to false,
        "4Rathmaul" to false,
        "4Tyrannis Glaive" to false,
        "4Ya-Ku Wrath" to false,
        "5Catastrophe\\'s Light" to false,
        "5Daora\\'s Tethidine" to false,
        "1Bone Lance" to false,
        "2Hard Bone Lance" to false,
        "2Steel Lance" to false,
        "3Aqua Horn" to false,
        "3Carapace Lance" to false,
        "3Chrome Lance" to false,
        "3Flame Lance" to false,
        "3Heavy Bone Lance" to false,
        "3Kulu Duda" to false,
        "3Thunder Lance" to false,
        "4Barroth Stinger" to false,
        "4Dancing Duval" to false,
        "4Icesteel Spear" to false,
        "4Lightning Spire" to false,
        "4Nergal Impaler" to false,
        "4Red Tail" to false,
        "4Water Spike" to false,
        "5Daora\\'s Fang" to false,
        "5Perdition\\'s Hand" to false,
        "1Hunter\\'s Rifle" to false,
        "2Hight Chain Blitz" to false,
        "2Power Rifle" to false,
        "3Carapace Rifle" to false,
        "3Cross Blitz" to false,
        "3Flame Blitz" to false,
        "3Jagras Blitz" to false,
        "3Madness Rifle" to false,
        "3Sniper Shot" to false,
        "4Barroth Shot" to false,
        "4Icesteel Wasp" to false,
        "4Jagras Fire" to false,
        "4Jyura Bullet" to false,
        "4Nergal Spitter" to false,
        "4Rathbuster" to false,
        "5Cataclysm\'s Trigger" to false,
        "5Daora\\'s Hornet" to false,
        "1Bone Shotel" to false,
        "2Hard Bone Shotel" to false,
        "2Iron Grace" to false,
        "3Blazing Shotel" to false,
        "3Bone Reaper" to false,
        "3First Dance" to false,
        "3Iron Gospel" to false,
        "3Jyura Shotel" to false,
        "3Pulsar Shotel" to false,
        "3Wyvern Blade \"Fall\"" to false,
        "4Anja Scimitar" to false,
        "4Dipterus" to false,
        "4Imperial Saber" to false,
        "4Kadachi Fang" to false,
        "4Last Dance" to false,
        "4Nergal Reaver" to false,
        "4Wyvern Blade \"Blood\"" to false,
        "5Extermination\\'s Edge" to false,
        "5Imperial Shimmer" to false,
        "1Bone Axe" to false,
        "2Bone Smasher" to false,
        "2Improved Steel Axe" to false,
        "3Carapace Axe" to false,
        "3Diablos Axe" to false,
        "3Flammenbeil" to false,
        "3Perfected Alloy Axe" to false,
        "3Power Smasher" to false,
        "3Rathalos Axe" to false,
        "4Axe Semper Tyrannis" to false,
        "4Barroth Grinder" to false,
        "4Gnashing Flammenbeil" to false,
        "4Nergal Gash" to false,
        "4Rathbringer Axe" to false,
        "4Teostra\\'s Arx" to false,
        "5Dying Light" to false,
        "5Teostra\\'s Castle" to false,
        "1Bone Kukri" to false,
        "2Chief Kukri" to false,
        "2Steel Knife" to false,
        "3Blooming Knife" to false,
        "3Carapace Edge" to false,
        "3Chrome Slicer" to false,
        "3Flame Knife" to false,
        "3Grand Barong" to false,
        "3Jagras Edge" to false,
        "4Barroth Club" to false,
        "4Datura Blossom" to false,
        "4Heat Edge" to false,
        "4Jagras Garrotte" to false,
        "4Nergal Jack" to false,
        "4Teostra\\'s Spada" to false,
        "5Eradication Vanguard" to false,
        "5Teostra\\'s Emblem" to false
    ),
    val helmList: Map<String, Boolean> = mapOf<String, Boolean>(
        "Alloy Helm" to false,
        "Bone Helm" to false,
        "Anja Helm" to false,
        "Barroth Helm" to false,
        "Jagras Helm" to false,
        "Jyura Helm" to false,
        "Kadachi Helm" to false,
        "Kulu Headpiece" to false,
        "Pukei Hood" to false,
        "Diablos Helm" to false,
        "Diablos Nero Helm" to false,
        "Rathalos Helm" to false,
        "Rath Soul Helm" to false,
        "Kushala Glare" to false,
        "Nergigante Helm" to false,
        "Kaiser Crown" to false
    ),
    val chestList: Map<String, Boolean> = mapOf<String, Boolean>(
        "Alloy Mail" to false,
        "Bone Mail" to false,
        "Anja Mail" to false,
        "Barroth Mail" to false,
        "Jagras Mail" to false,
        "Jyura Mail" to false,
        "Kadachi Mail" to false,
        "Kulu Mail" to false,
        "Pukei Mail" to false,
        "Diablos Mail" to false,
        "Diablos Nero Mail" to false,
        "Rathalos Mail" to false,
        "Rath Soul Mail" to false,
        "Kushala Cista" to false,
        "Nergigante Mail" to false,
        "Kaiser Mail" to false
    ),
    val legsList: Map<String, Boolean> = mapOf<String, Boolean>(
        "Alloy Greaves" to false,
        "Bone Greaves" to false,
        "Anja Greaves" to false,
        "Barroth Greaves" to false,
        "Jagras Greaves" to false,
        "Jyura Greaves" to false,
        "Kadachi Greaves" to false,
        "Kulu Greaves" to false,
        "Pukei Greaves" to false,
        "Diablos Greaves" to false,
        "Diablos Nero Greaves" to false,
        "Rathalos Greaves" to false,
        "Rath Soul Greaves" to false,
        "Kushala Crus" to false,
        "Nergigante Greaves" to false,
        "Kaiser Greaves" to false
    ),
    val materialsList: Map<String, Int> = mapOf<String, Int>(
        "Anjanath Fang" to 0,
        "Anjanath Nosebone" to 0,
        "Anjanath Pelt" to 0,
        "Anjanath Scale" to 0,
        "Anjanath Tail" to 0,
        "Azure Rath Carapace" to 0,
        "Azure Rath Marrow" to 0,
        "Azure Rath Plate" to 0,
        "Azure Rath Scale" to 0,
        "Azure Rath Tail" to 0,
        "Azure Rath Wing" to 0,
        "Azure Rath Wingtalon" to 0,
        "Barroth Carapace" to 0,
        "Barroth Claw" to 0,
        "Barroth Ridge" to 0,
        "Barroth Shell" to 0,
        "Black Diab Carapace" to 0,
        "Black Diab Ridge" to 0,
        "Daora Carapace" to 0,
        "Daora Claw" to 0,
        "Daora Dragon Scale" to 0,
        "Daora Gem" to 0,
        "Daora Horn" to 0,
        "Daora Tail" to 0,
        "Daora Webbing" to 0,
        "Diablos Carapace" to 0,
        "Diablos Fang" to 0,
        "Diablos Ridge" to 0,
        "Diablos Shell" to 0,
        "Great Jagras Claw" to 0,
        "Great Jagras Hide" to 0,
        "Great Jagras Mane" to 0,
        "Great Jagras Scale" to 0,
        "Jyuratodas Carapace" to 0,
        "Jyuratodas Fang" to 0,
        "Jyuratodas Fin" to 0,
        "Jyuratodas Scale" to 0,
        "Jyuratodas Shell" to 0,
        "Kadachi Claw" to 0,
        "Kadachi Electrode" to 0,
        "Kadachi Membrane" to 0,
        "Kadachi Pelt" to 0,
        "Kadachi Scale" to 0,
        "Kulu-Ya-Ku Beak" to 0,
        "Kulu-Ya-Ku Hide" to 0,
        "Kulu-Ya-Ku Plume" to 0,
        "Kulu-Ya-Ku Scale" to 0,
        "Nerg Carapace" to 0,
        "Nerg Gem" to 0,
        "Nerg Horn" to 0,
        "Nerg Regrowth Plate" to 0,
        "Nerg Tail" to 0,
        "Nerg Talon" to 0,
        "Pukei Carapace" to 0,
        "Pukei Quill" to 0,
        "Pukei Scale" to 0,
        "Pukei Sac" to 0,
        "Pukei Tail" to 0,
        "Pukei Wing" to 0,
        "Rathalos Carapace" to 0,
        "Rathalos Marrow" to 0,
        "Rathalos Medulla" to 0,
        "Rathalos Plate" to 0,
        "Rathalos Scale" to 0,
        "Rathalos Shell" to 0,
        "Rathalos Tail" to 0,
        "Rathalos Webbing" to 0,
        "Rathalos Wing" to 0,
        "Rathalos Wingtalon" to 0,
        "Teostra Carapace" to 0,
        "Teostra Claw" to 0,
        "Teostra Gem" to 0,
        "Teostra Horn" to 0,
        "Teostra Mane" to 0,
        "Teostra Powder" to 0,
        "Teostra Tail" to 0,
        "Teostra Webbing" to 0
    ),
    val MonsterPartsList: Map<String, Int> = mapOf<String, Int>(
        "Ancient Bone" to 0,
        "Aqua Sac" to 0,
        "Bird Wyvern Gem" to 0,
        "Black Spiral Horn" to 0,
        "Blos Medulla" to 0,
        "Boulder Bone" to 0,
        "Carablite Ore" to 0,
        "Coral Crystal" to 0,
        "Dragonite Ore" to 0,
        "Dragonvein Crystal" to 0,
        "Earth Crystal" to 0,
        "Elder Dragon Blood" to 0,
        "Elder Dragon Bone" to 0,
        "Electrode" to 0,
        "Electro Sac" to 0,
        "Fertile Mud" to 0,
        "Firecell Stone" to 0,
        "Fire Dragon Scale" to 0,
        "Flame Sac" to 0,
        "Fucium Ore" to 0,
        "Gajau Scale" to 0,
        "Immortal Dragonscale" to 0,
        "Inferno Sac" to 0,
        "Majestic Horn" to 0,
        "Malachite Ore" to 0,
        "Monster Bone Large" to 0,
        "Monster Bone Medium" to 0,
        "Monster Bone Small" to 0,
        "Monster Hardbone" to 0,
        "Monster Keenbone" to 0,
        "Novacrystal" to 0,
        "Piercing Claw" to 0,
        "Poison Sac" to 0,
        "Quality Bone" to 0,
        "Sharp Claw" to 0,
        "Thunder Sac" to 0,
        "Toxin Sac" to 0,
        "Twisted Horn" to 0,
        "Warm Pelt" to 0,
        "Wingdrake Hide" to 0,
        "Wyvern Gem" to 0
    ),
    val QuestList: Map<String, Int> = mapOf<String, Int>(
        "Barroth*" to 0,
        "Barroth**" to 0,
        "Barroth***" to 0,
        "Great Jagras*" to 0,
        "Great Jagras**" to 0,
        "Great Jagras***" to 0,
        "Kulu-Ya-Ku*" to 0,
        "Kulu-Ya-Ku**" to 0,
        "Kulu-Ya-Ku***" to 0,
        "Pukei-Pukei*" to 0,
        "Pukei-Pukei**" to 0,
        "Pukei-Pukei***" to 0,
        "Tobi-Kadachi*" to 0,
        "Tobi-Kadachi**" to 0,
        "Tobi-Kadachi***" to 0,
        "Anjanath*" to 0,
        "Anjanath**" to 0,
        "Anjanath***" to 0,
        "Jyuratodus*" to 0,
        "Jyuratodus**" to 0,
        "Jyuratodus***" to 0,
        "Azure Rathalos*" to 0,
        "Azure Rathalos**" to 0,
        "Azure Rathalos****" to 0,
        "Black Diablos*" to 0,
        "Black Diablos**" to 0,
        "Black Diablos****" to 0,
        "Diablos*" to 0,
        "Diablos**" to 0,
        "Diablos****" to 0,
        "Rathalos*" to 0,
        "Rathalos**" to 0,
        "Rathalos****" to 0,
        "Kushala Daora*" to 0,
        "Kushala Daora**" to 0,
        "Kushala Daora*****" to 0,
        "Nergigante*" to 0,
        "Nergigante**" to 0,
        "Nergigante*****" to 0,
        "Teostra*" to 0,
        "Teostra**" to 0,
        "Teostra*****" to 0
    )
) {
    @Exclude
    fun toMap(): Map<String, Any?> {
        return mapOf(
            "id" to id,
            "playerName" to playerName,
            "characterName" to characterName,
            "campaignName" to campaignName,
            "palicoName" to palicoName,
            "weaponType" to weaponType,
            "potionCount" to potionCount,
            "dayCount" to dayCount,
            "weaponList" to weaponList,
            "helmList" to helmList,
            "chestList" to chestList,
            "legsList" to legsList,
            "materialsList" to materialsList,
            "MonsterPartsList" to MonsterPartsList,
            "QuestList" to QuestList
        )
    }
}

